name: therewasanattempt

on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  memes:
    name: insanepeoplefacebook
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install FFmpeg
      run: >
        sudo apt-get update &&
        sudo add-apt-repository ppa:jonathonf/ffmpeg-4 -yu &&
        sudo apt-get install ffmpeg

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.x"

    - name: Install Python dependencies
      run: python -m pip install -r requirements.txt

    - name: Create video
      env:
        praw_client_id: ${{ secrets.REDDIT_CLIENT_ID }}
        praw_client_secret: ${{ secrets.REDDIT_CLIENT_SECRET }}
        praw_user_agent: ${{ secrets.REDDIT_USER_AGENT }}
        YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
        YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
        YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
      run: >
        python3 sparkmemes.py "r/therewasanattempt v{}" 65
        --subreddits "therewasanattempt"
        --tags "There Was An Attempt - EPIC FAILS" "reddit" "funny"
        "epic fails" "epic" "fails" "funny fails" "r/" "giofilms" "sorrow tv"
        "rslash" "comedy" "memes" "dank doodle memes" "ddm" "best posts"
        "top reddit posts" "reddit stories" "cringe" "reddit cringe"
        "funniest" "fail"
