name: "therewasanattempt"

on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  memes:
    name: "therewasanattempt"
    runs-on: "windows-latest"
    timeout-minutes: 30
    steps:

    - name: "Checkout repository"
      uses: "actions/checkout@v2"

    - name: "Install Daniel UK TTS"
      run: "res/tts/DanielUK.msi /i /quiet /qn"
      continue-on-error: true

    - name: "Install dependencies"
      run: "choco install --no-progress ffmpeg"
    - name: "Setup Python"
      uses: "actions/setup-python@v2"
      with:
        python-version: "3.x"

    - name: "Install Python dependencies"
      run: "python -m pip install -r requirements.txt"

    - name: "Create video"
      env:
        praw_client_id: ${{ secrets.REDDIT_CLIENT_ID }}
        praw_client_secret: ${{ secrets.REDDIT_CLIENT_SECRET }}
        praw_user_agent: ${{ secrets.REDDIT_USER_AGENT }}
        YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
        YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
        YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
      run: >
        python -m sparkmemes "r/therewasanattempt v{}" "65"
        --subreddits "therewasanattempt"
        --tags "There Was An Attempt - EPIC FAILS" "reddit" "funny"
        "epic fails" "fails" "funny fails" "r/" "giofilms" "sorrow tv" "rslash"
        "comedy" "dank doodle memes" "ddm" "best posts" "top reddit posts"
        "reddit stories" "reddit cringe" "funniest" "fail"
