name: Epicly dank memes

on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  memes:
    name: Epicly dank memes
    runs-on: windows-latest
    timeout-minutes: 15
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install FFmpeg
      run: choco install ffmpeg tesseract --pre
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Install Python dependencies
      run: python -m pip install -r requirements.txt

    - name: Create video
      env:
        praw_client_id: ${{ secrets.REDDIT_CLIENT_ID }}
        praw_client_secret: ${{ secrets.REDDIT_CLIENT_SECRET }}
        praw_user_agent: ${{ secrets.REDDIT_USER_AGENT }}
        YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
        YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
        YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
      run: >
        python -m sparkmemes "Epicly dank memes v{}" 16
        --subreddits "dankmemes" "me_irl" "meirl" "memes" "wholesomememes"
        "MemeEconomy" "BikiniBottomTwitter"
        --tags "memes" "dank doodle memes" "best memes" "memes compilation"
        "dank memes" "memes 2019" "funny memes" "dank memes compilation"
        "best memes compilation" "meme" "funny" "fortnite memes"
        "tik tok ironic memes compilation" "freememeskids" "pewdiepie"
        "try not to laugh challenge" "you laugh you lose challenge"
        "funniest memes" "ddm" "memes i like to watch"
        "ultimate memes compilation" "dank" "compilation" "tik tok memes"
        "2019" "meme review" "dog memes" "cat memes" "spongebob memes" "tiktok"
        "memes to watch"
