name: Memes

on:
  schedule:
    - cron: "0 8 * * *"
  push:

jobs:
  memes:
    name: Memes
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Create memes
      env:
        praw_client_id: ${{ secrets.REDDIT_CLIENT_ID }}
        praw_client_secret: ${{ secrets.REDDIT_CLIENT_SECRET }}
        praw_user_agent: ${{ secrets.REDDIT_USER_AGENT }}
        YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
        YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
        YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
      run: |
        choco install ffmpeg --no-progress
        python -m pip install -r requirements.txt
        python sparkmemes.py "Epicly dank memes v{}"
