name: Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install FFmpeg
      run: brew install ffmpeg
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Install Python dependencies
      run: python -m pip install -r requirements.txt

    - name: Create video
      env:
        praw_client_id: ${{ secrets.REDDIT_CLIENT_ID }}
        praw_client_secret: ${{ secrets.REDDIT_CLIENT_SECRET }}
        praw_user_agent: ${{ secrets.REDDIT_USER_AGENT }}
      run: python -m sparkmemes

    - name: Upload stuff
      uses: actions/upload-artifact@v2
      with:
        path: "video.mp4"
