name: "Funny r/woooosh moments"

on:
  schedule:
    - cron: "0 20 * * *"

jobs:
  memes:
    name: "Funny r/woooosh moments"
    runs-on: "windows-latest"
    timeout-minutes: 30
    steps:

    - name: "Checkout repository"
      uses: "actions/checkout@v2"

    - name: "Install dependencies"
      run: "choco install --no-progress ffmpeg"
    - name: "Setup Python"
      uses: "actions/setup-python@v2"
      with:
        python-version: "3.x"

    - name: "Install Python dependencies"
      run: "python -m pip install -r requirements.txt"

    - name: "Create video"
      env:
        praw_client_id: ${{ secrets.REDDIT_CLIENT_ID }}
        praw_client_secret: ${{ secrets.REDDIT_CLIENT_SECRET }}
        praw_user_agent: ${{ secrets.REDDIT_USER_AGENT }}
        YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
        YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
        YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
      run: >
        python -m sparkmemes "Funny r/woooosh moments v{}" "21"
        --subreddits "woooosh"
        --tags "r/woosh" "r/wooosh" "over their heads" "not getting the joke"
        "reddit" "woooosh" "top reddit posts" "best reddit posts"
        "r/woooosh top posts" "funny" "interesting" "memes" "jokes"
        "best posts" "dank doodle memes" "giofilms" "emkay" "sorrowtv"
